# permissions for end users to edit operatorresourcemappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatorresourcemapping-editor-role
rules:
- apiGroups:
  - turbonomic.io
  resources:
  - operatorresourcemappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - turbonomic.io
  resources:
  - operatorresourcemappings/status
  verbs:
  - get
